config/routes.rb
Rails.application.routes.draw do
  root "dashboard#index"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users do
    resources :subscriptions
    resources :tags
    resources :payment_methods
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :subscription_tags, dependent: :destroy
  has_many :subscriptions, through: :subscription_tags

  validates :name, presence: true

  scope :search_by_name, ->(query) { where("name LIKE ?", "%#{query}%") }
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :logged_in_user
  before_action :correct_user
  before_action :get_tag, only: %i[destroy edit update]

  def index
    @tags = Tag.search_by_name(query_params[:name])
    @tag = Tag.new
  end

  def create
    @tag = Tag.new(tag_params)
    if @tag.save
      flash[:success] = "タグを作成しました"
      redirect_to user_tags_path(current_user)
    else
      @tags = Tag.all
      render "index", status: :unprocessable_entity
    end
  end

  def edit
    if @tag.nil?
      flash[:danger] = "タグが見つかりませんでした"
      redirect_to user_tags_path(current_user)
    end
  end

  def update
    if @tag.update(tag_params)
      flash[:success] = "タグを更新しました"
      redirect_to user_tags_path(current_user)
    else
      @tags = Tag.all
      render "index", status: :unprocessable_entity
    end
  end

  def destroy
    if @tag.destroy
      flash[:success] = "タグを削除しました"
      redirect_to user_tags_path(current_user)
    else
      flash.now[:danger] = "タグの削除に失敗しました"
      redirect_to user_tags_path(current_user)
    end
  end

  private

  def get_tag
    @tag = Tag.find_by(id: params[:id])
  end

  def tag_params
    params.require(:tag).permit(:name, :color)
  end

  def query_params
    params.permit(:name)
  end
end

app/helpers/tags_helper.rb
module TagsHelper
  def hex_to_rgba(hex_color, alpha)
    rgb = hex_color&.gsub("#", "").scan(/../).map { |color| color.to_i(16) }
    "rgba(#{rgb.join(", ")}, #{alpha})"
  end
end

app/views/tags/_tag.html.erb
<div id="<%= "tag_#{tag.id}" %>" class="g-col-12 g-col-md-4 tag-card p-3">
  <div class="card">
    <div class="card-header p-0 d-flex justify-content-between align-items-center">
      <span class="badge fs-6 px-2" style="color: <%= tag.color %>; border: 1px solid <%= tag.color %>; background-color: <%= tag.color.present? ? hex_to_rgba(tag.color, 0.3) : "" %>;"><%= tag.name %></span>
      <div class="d-flex">
        <div type="button" class="edit-tag-button" data-tag-id="<%= tag.id %>" data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-custom-class="custom-tooltip" data-bs-title="編集">
          <i class="bi bi-pencil"></i>
        </div>
        <%= button_to user_tag_path(current_user, id: tag.id),
                          method: :delete,
                          data: { 
                            turbo_confirm: "#{tag.name}を削除してもよろしいですか?", 
                            bs_toggle: 'tooltip', 
                            bs_placement: 'bottom', 
                            bs_custom_class: 'custom-tooltip', 
                            bs_title: '削除' 
                          } do %>
          <i class="bi bi-trash"></i>
        <% end %>
      </div>
    </div>
    <div class="card-body p-0 pt-2">
      <%= link_to user_subscriptions_path(current_user, id: tag.id), class: "text-decoration-none" do %>
        <div class="d-inline-block" data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-custom-class="custom-tooltip" data-bs-title="サブスクリプション数">
          <div class="d-flex align-items-center">
            <i class="bi bi-collection me-2"></i>
            <p class="card-text mb-0"><%= tag.subscriptions.count %></p>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/tags/edit.html.erb
<h1>タグ編集</h1>

<%= form_with(model: [@user, @tag]) do |f| %>
  <%= f.label :name, "名前" %>
  <%= f.text_field :name %>

  <%= f.submit "送信する" %>
<% end %>

app/views/tags/index.html.erb
<div id="tags_container">
  <div class="d-flex align-items-center gap-5 mb-3">
    <div class="d-flex align-items-center">
      <h3><%= Tag.model_name.human %></h3>
      <span class="tag-count"><%= @tags.count %></span>
    </div>
    <div class="w-50">
      <%= form_with(url: user_tags_path(current_user), method: :get) do |f| %>
        <%= f.text_field :name, value: params[:name], class: "form-control", placeholder: "#{Tag.model_name.human}を検索" %>
      <% end %>
    </div>
  </div>
  <div class="grid" style="--bs-gap: 3rem;">
    <div id="tags_list" class="g-col-12 g-col-md-9">
      <div class="grid" style="--bs-gap: 1rem;">
        <%= render @tags %>
      </div>
    </div>
    <div class="g-col-12 g-col-md-3">
      <div id="new_tag_form" class="card-style">
        <h3 class="mb-4">新規<%= Tag.model_name.human %></h3>
        <%= form_with(model: @tag, url: user_tags_path(current_user)) do |f| %>
          <%= render "shared/error_messages", object: f.object %>
          <div>
            <%= f.label :name %>
            <%= f.text_field :name, class: "form-control", placeholder: "例: 音楽" %>
          </div>
          <div>
            <%= f.label :color %>
            <%= f.color_field :color, class: "form-control" %>
          </div>
          <button type="submit" class="btn submit-btn" name="commit" id="new_tag_submit" data-disable-with="<%= Tag.model_name.human %>を作成">
            <i class="bi bi-plus-lg text-white me-2"></i>
            <%= Tag.model_name.human %>を作成
          </button>
        <% end %>
      </div>
      <% @tags.each do |tag| %>
        <div id="edit_tag_form_<%= tag.id %>" style="display: none;" class="card-style">
          <h3 class="mb-4"><%= Tag.model_name.human %>編集</h3>
          <%= form_with(model: tag, url: user_tag_path(current_user, tag)) do |f| %>
            <%= render "shared/error_messages", object: f.object %>
            <div>
              <%= f.label :name %>
              <%= f.text_field :name, class: "form-control", placeholder: "例: 音楽", id: "tag_name_#{tag.id}" %>
            </div>
            <div>
              <%= f.label :color %>
              <%= f.color_field :color, class: "form-control" %>
            </div>
            <div class="d-flex align-items-end gap-3">
              <button type="button" class="btn cancel-edit" data-tag-id="<%= tag.id %>" id="cancel_edit_button">キャンセル</button>
              <button type="submit" class="btn submit-btn" name="commit" id="edit_tag_submit" data-disable-with="<%= Tag.model_name.human %>を更新" data-tag-id="<%= tag.id %>">
                <i class="bi bi-pencil-square text-white me-2"></i>
                更新
              </button>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>