config/routes.rb
Rails.application.routes.draw do
  root "dashboard#index"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users do
    resources :subscriptions
    resources :tags
    resources :payment_methods
  end
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  enum :status, { active: 0, canceled: 1, expired: 2, trial: 3 }

  belongs_to :user
  belongs_to :payment_method, optional: true
  has_many :subscription_tags, dependent: :destroy
  has_many :tags, through: :subscription_tags
  has_many :payments, dependent: :destroy

  validates :name, presence: true
  validates :plan, presence: true
  validates :price, presence: true
  validates :start_date, presence: true
  # validates :end_date, presence: true
  validates :billing_day_of_month, presence: true
  # validate :end_date_after_start_date

  scope :billing_in_this_month, ->(user) {
    where(user_id: user).where("billing_day_of_month BETWEEN :start_date AND :end_date",
      start_date: Date.today.beginning_of_month, end_date: Date.today.end_of_month)
  }
  scope :next_billing_soon, ->(user) {
    where("billing_day_of_month > ? AND user_id = ?", Date.today, user)
      .order(billing_day_of_month: :asc)
      .includes(:tags)
      .limit(10)
  }
  scope :latest, ->(user) {
    where(user_id: user)
      .order(created_at: :desc)
      .limit(5)
      .includes(:tags, :payment_method)
  }

  def self.this_month_total_billing(user)
    billing_in_this_month(user).sum(:price)
  end

  private

  def end_date_after_start_date
    return if end_date.blank? || start_date.blank?

    if end_date <= start_date
      errors.add(:end_date, "終了日は開始日より後の日付に設定してください")
    end
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :logged_in_user
  before_action :correct_user
  before_action :get_subscription, only: %i[edit update destroy show]

  def index
    @search_subscription_form = SearchSubscriptionForm.new(search_subscription_params, current_user: current_user)
    unless @search_subscription_form.valid?
      return @subscriptions = []
    end

    @subscriptions = @search_subscription_form.search_subscriptions
  end

  def show
  end

  def new
    @subscription = current_user.subscriptions.new
  end

  def create
    @subscription = current_user.subscriptions.new(subscription_params.except(:create_initial_payment))

    ActiveRecord::Base.transaction do
      if params.dig(:subscription, :create_initial_payment) == "1"
        @subscription.billing_date = @subscription.start_date.advance(months: @subscription.billing_cycle.to_i)
        @subscription.save!
        @subscription.payments.create!(
          billing_date: @subscription.start_date,
          amount: @subscription.price,
          plan: @subscription.plan,
          billing_cycle: @subscription.billing_cycle,
          payment_method_id: @subscription.payment_method_id
        )
      else
        @subscription.billing_date = @subscription.start_date
        @subscription.save!
      end

      flash[:success] = "サブスクリプションが登録されました"
      redirect_to root_path
    rescue ActiveRecord::RecordInvalid => e
      @subscription = e.record
      render "new", status: :unprocessable_entity
    end
  end

  def edit
    if @subscription.nil?
      flash[:danger] = "サブスクリプションが見つかりませんでした"
      redirect_to root_path
    else
      @tags = Tag.all
      @payment_methods = current_user.payment_methods
    end
  end

  def update
    params[:subscription][:tag_ids] ||= []
    if @subscription.update(subscription_params)
      flash[:success] = "サブスクリプションを更新しました"
      redirect_to root_path
    else
      render "edit", status: :unprocessable_entity
    end
  end

  def destroy
    if @subscription.destroy
      flash[:success] = "サブスクリプションを削除しました"
      redirect_to user_subscriptions_path(current_user)
    else
      flash[:danger] = "サブスクリプションの削除に失敗しました"
      redirect_to user_subscription_path(current_user)
    end
  end

  private

  def subscription_params
    params.require(:subscription).permit(:name,
      :plan,
      :price,
      :status,
      :start_date,
      :end_date,
      :billing_day_of_month,
      :payment_method_id,
      :billing_cycle,
      :create_initial_payment,
      tag_ids: [])
  end

  def get_subscription
    @subscription = Subscription.find_by(id: params[:id])
  end

  def search_subscription_params
    params.fetch(:q, {}).permit(:filter_column,
      :text_filter_value,
      :text_filter_pattern,
      :date_filter_start,
      :date_filter_end,
      :date_filter_pattern,
      :first_column,
      :first_direction,
      :second_column,
      :second_direction,
      :page)
  end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_form.html.erb
<div id="edit-subscription" class="container">
  <h2 class="mb-4"><%= model.new_record? ? "新規作成" : "編集" %></h2>
  <%= form_with model:, url: do |f| %>
    <div class="d-flex flex-column gap-4">
      <%= render "shared/error_messages", object: f.object %>
      <div class="card-border p-4">
        <h3>基本情報</h3>
        <p class="section-description">サブスクリプションの基本情報を入力してください。</p>
        <div class="d-flex justify-content-between gap-2 mb-3">
          <div class="d-flex flex-column w-100">
            <%= f.label :name, class: "form-label" %>
            <%= f.text_field :name, class: "form-control" %>
          </div>
          <div class="d-flex flex-column w-100">
            <%= f.label :price, class: "form-label" %>
            <%= f.number_field :price, class: "form-control" %>
          </div>
        </div>
        <div class="d-flex justify-content-between gap-2 mb-3">
          <div class="d-flex flex-column w-100">
            <%= f.label :plan, class: "form-label" %>
            <%= f.text_field :plan, class: "form-control" %>
          </div>
          <div class="d-flex flex-column w-100">
            <%= f.label :billing_cycle, class: "form-label" %>
            <%= f.number_field :billing_cycle, class: "form-control", min: 1 %>
          </div>
        </div>
        <div class="mt-3">
          <h6><%= Subscription.human_attribute_name(:status) %></h6>
          <div class="d-flex gap-4 mt-3">
            <% Subscription.statuses_i18n.invert.each do |translated_status, enum_key| %>
              <div>
                <%= radio_button_tag "subscription[status]", enum_key, @subscription&.status == enum_key, id: "status_#{enum_key}" %>
                <%= label_tag "status_#{enum_key}", translated_status, class: "form-label" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
      <div class="card-border p-4">
        <h3>請求情報</h3>
        <p class="section-description">請求日や支払い方法などを設定してください。</p>
        <div class="grid mb-3">
          <div class="d-flex flex-column g-col-12 g-col-md-4">
            <%= f.label :billing_day_of_month, class: "form-label" %>
            <%= f.number_field :billing_day_of_month, class: "form-control", min: 1, max: 31 %>
          </div>
          <div class="d-flex flex-column g-col-12 g-col-md-4">
            <%= f.label :start_date, class: "form-label" %>
            <%= f.date_field :start_date, class: "form-control" %>
          </div>
<!--          <div class="d-flex flex-column g-col-12 g-col-md-4">-->
            <%#= f.label :end_date, class: "form-label" %>
            <%#= f.date_field :end_date, class: "form-control" %>
<!--          </div>-->
        </div>
        <div class="my-3">
          <%= check_box_tag "subscription[create_initial_payment]", "1", false, class: "form-check-input" %>
          <%= label_tag "subscription_create_initial_payment", "利用開始日に初回支払いがあった場合は、チェックを入れてください", class: "form-check-label" %>
        </div>
        <p><%= PaymentMethod.model_name.human %></p>
        <% current_user.payment_methods.each do |payment_method| %>
          <div>
            <%= radio_button_tag "subscription[payment_method_id]",
                                 payment_method.id, @subscription.payment_method == payment_method,
                                 id: "payment_method_#{payment_method.id}" %>
            <%= label_tag "payment_method_#{payment_method.id}",
                          [payment_method.method_type, payment_method.provider, payment_method.memo].reject(&:blank?).join(', '),
                          class: "form-label" %>
          </div>
        <% end %>
      </div>
      <div class="card-border p-4">
        <h3><%= Tag.model_name.human %></h3>
        <p class="section-description">該当するタグを選択してください。</p>
        <div class="d-flex flex-wrap gap-4 mt-3">
          <% Tag.all.each do |tag| %>
            <div>
              <%= check_box_tag "subscription[tag_ids][]", tag.id, @subscription.tags.include?(tag), id: "tag_#{tag.id}" %>
              <%= label_tag "tag_#{tag.id}", tag.name, class: "form-label" %>
            </div>
          <% end %>
        </div>
      </div>
      <div class="grid text-center mt-4">
        <div class="g-col-3 g-start-3">
          <%= link_to "キャンセル", user_subscriptions_path(@user), id: "cancel_edit_button", class: "btn w-100" %>
        </div>
        <div class="g-col-3 g-start-8">
          <%= f.submit model.new_record? ? "新規作成": "変更を保存", id: "edit_subscription_submit", class: "btn w-100" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/subscriptions/_subscription.html.erb
<div class="g-col-12 g-col-md-3">
  <div class="card p-3" id="subscription-card">
    <div class="card-header">
      <% link_path ||= user_subscription_path(current_user, subscription) %>
      <h3><%= link_to subscription.name, link_path %></h3>
      <span><%= subscription.plan %></span>
    </div>
    <hr>
    <div class="card-body">
      <div class="info-group">
        <span>
          <i class="bi bi-calendar-range me-2"></i>期間
        </span>
        <p class="card-text"><%= subscription.start_date&.strftime('%Y年%m月%d日') %> ~ <%= subscription.end_date&.strftime('%Y年%m月%d日') %></p>
      </div>
      <div class="info-group">
        <span>
          <i class="bi bi-calendar-range me-2"></i>次回請求日
        </span>
        <p class="card-text"><%= subscription.billing_date&.strftime('%Y年%m月%d日') %></p>
      </div>
      <div class="info-group">
        <span>
          <i class="bi bi-credit-card me-2"></i><%= Subscription.human_attribute_name(:billing_day_of_month) %>
        </span>
        <p class="card-text"><%= subscription.billing_day_of_month %>日</p>
      </div>
      <div class="info-group">
        <span>
          <i class="bi bi-calendar-plus me-2"></i><%= Subscription.human_attribute_name(:created_at) %>
        </span>
        <p class="card-text"><%= subscription.created_at.strftime('%Y年%m月%d日') %></p>
      </div>
      <div class="d-flex justify-content-end">
        <h5 class="card-text price">¥<%= number_with_delimiter(subscription.price.to_i) %> / 月</h5>
      </div>
    </div>
    <% if subscription.payment_method.present? || subscription.tags.any? %>
      <hr>
      <div class="card-footer">
        <div class="footer-content">
          <% if subscription.tags.any? %>
            <div class="tag-container">
              <% subscription.tags.each do |tag| %>
                <span class="badge fs-6 px-2" style="color: <%= tag.color %>; border: 1px solid <%= tag.color %>; background-color: <%= tag.color.present? ? hex_to_rgba(tag.color, 0.3) : "" %>;"><%= tag.name %></span>
              <% end %>
            </div>
          <% end %>
          <% if subscription.payment_method.present? %>
            <div class="info-group">
              <span><%= PaymentMethod.model_name.human %></span>
              <p><%= subscription.payment_method.provider %></p>
            </div>
          <% end %>
        </div>
      </div>
      <% if content_for?(:subscription_actions) %>
        <%= yield :subscription_actions %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/subscriptions/edit.html.erb
<%= render 'form', model: @subscription, url: user_subscription_path(@user, @subscription) %>

app/views/subscriptions/index.html.erb
<div id="subscription-container">
  <%= form_with(model: @search_subscription_form, url: user_subscriptions_path(current_user), scope: :q, method: :get) do |f| %>
    <div id="search_row" class="grid">
      <div class="g-col-12 g-col-md-10">
        <%= f.search_field :text_filter_value, placeholder: "サブスクリプションを検索", class: "form-control w-100" %>
      </div>
      <div class="g-col-12 g-col-md-2 text-end">
        <%= render "shared/error_messages", object: @search_subscription_form %>
        <div>
          <button type="button" id="open_filter_box" class="btn btn-outline-secondary">フィルター</button>
          <div id="filter_box" style="display: none;">
            <div class="d-flex justify-content-between gap-2 mb-3">
              <div>
                <div class="text-start">
                  <%= f.label :filter_column, "フィルター", class: "form-label" %>
                </div>
                <%= f.select :filter_column, [["選択してください", ""],
                                              [Subscription.human_attribute_name(:name), "name"],
                                              [Subscription.human_attribute_name(:plan), "plan"],
                                              [Subscription.human_attribute_name(:price), "price"],
                                              [Subscription.human_attribute_name(:start_date), "start_date"],
                                              [Subscription.human_attribute_name(:end_date), "end_date"],
                                              [Subscription.human_attribute_name(:billing_day_of_month), "billing_day_of_month"]], {},
                             class: "form-select" %>
              </div>
              <div class="d-flex align-items-end">
                <div id="text_filter_pattern" style="display: none;">
                  <%= f.select :text_filter_pattern, [["完全一致", "exact"],
                                                      ["部分一致", "partial"],
                                                      ["前方一致", "start_with"],
                                                      ["後方一致", "end_with"]], {},
                               selected: "partial",
                               class: "form-select"
                  %>
                </div>
              </div>
              <div class="d-flex align-items-end">
                <div id="date_filter_fields" style="display: none;">
                  <%= f.select :date_filter_pattern, [["完全一致", "exact"],
                                                      ["指定日より前", "before"],
                                                      ["指定日より後", "after"],
                                                      ["期間指定", "between"]], {},
                               class: "form-select"
                  %>
                </div>
              </div>
            </div>
            <div id="q_text_filter_patter" style="display: none;" class="mb-2">
              <div class="d-flex flex-column text-start gap-1 mb-1">
                <%= f.label :date_filter_start, Subscription.human_attribute_name(:start_date), class: "form-label" %>
                <%= f.date_field :date_filter_start, class: "form-control" %>
              </div>
              <div id="date_filter_end_field" style="display: none;">
                <div class="d-flex flex-column text-start gap-1">
                  <%= f.label :date_filter_end, Subscription.human_attribute_name(:end_date), class: "form-label" %>
                  <%= f.date_field :date_filter_end, class: "form-control" %>
                </div>
              </div>
            </div>
            <div id="text_filter_fields" style="display: none;" class="mb-3">
              <%= f.search_field :text_filter_value, placeholder: "検索値を入力してください", class: "w-100 form-control" %>
            </div>
            <%= f.submit "フィルターを追加", class: "btn btn-outline-secondary w-100", id: "add_filter_button" %>
          </div>
          <button type="button" id="open_sort_box" class="btn btn-outline-secondary">並び替え</button>
          <div id="sort_box" style="display: none;">
            <div class="text-start">
              <%= f.label :first_column, "並び替え（優先）", class: "form-label" %>
            </div>
            <div class="d-flex justify-content-between mb-3">
              <div>
                <%= f.select :first_column, [["選択してください", ""],
                                             [Subscription.human_attribute_name(:name), "name"],
                                             [Subscription.human_attribute_name(:plan), "plan"],
                                             [Subscription.human_attribute_name(:price), "price"],
                                             [Subscription.human_attribute_name(:start_date), "start_date"],
                                             [Subscription.human_attribute_name(:end_date), "end_date"],
                                             [Subscription.human_attribute_name(:billing_day_of_month), "billing_day_of_month"]], {},
                             class: "form-select" %>
              </div>
              <div>
                <%= f.select :first_direction, [
                  %w[降順 desc],
                  %w[昇順 asc]], {}, selected: "desc",
                             class: "form-select" %>
              </div>
            </div>
            <div class="text-start">
              <%= f.label :second_column, "並び替え（第2条件）", class: "form-label" %>
            </div>
            <div class="d-flex justify-content-between mb-3">
              <div>
                <%= f.select :second_column, [["選択してください", ""],
                                              [Subscription.human_attribute_name(:name), "name"],
                                              [Subscription.human_attribute_name(:plan), "plan"],
                                              [Subscription.human_attribute_name(:price), "price"],
                                              [Subscription.human_attribute_name(:start_date), "start_date"],
                                              [Subscription.human_attribute_name(:end_date), "end_date"],
                                              [Subscription.human_attribute_name(:billing_day_of_month), "billing_day_of_month"]], {},
                             class: "form-select" %>
              </div>
              <div>
                <%= f.select :second_direction, [
                  %w[降順 desc],
                  %w[昇順 asc]], {}, selected: "desc",
                             class: "form-select" %>
              </div>
            </div>
            <%= f.submit "並び替え条件を追加", id: "add_sort_button", class: "btn btn-outline-secondary w-100" %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <% if @subscriptions.any? %>
    <div class="grid g-4 mt-5">
      <%= render @subscriptions %>
      <%= will_paginate @subscriptions %>
    </div>
  <% else %>
    <div>
      <h3>登録されたサブスクリプションはありません</h3>
      <%= link_to "新規作成", new_user_subscription_path(current_user) %>
    </div>
  <% end %>
</div>

app/views/subscriptions/new.html.erb
<%= render 'form', model: @subscription, url: user_subscriptions_path %>

app/views/subscriptions/show.html.erb
<% content_for :subscription_actions do %>
  <div class="d-flex justify-content-end gap-3">
    <%= link_to "編集", edit_user_subscription_path(current_user, @subscription), class: "btn btn-outline-secondary" %>
    <%= link_to "削除", user_subscription_path(current_user, @subscription), method: :delete, data: { confirm: "本当に削除しますか？" }, class: "btn btn-outline-secondary" %>
  </div>
<% end %>

<div class="container pt-5">
  <%= render @subscription, link_path: edit_user_subscription_path(@user, @subscription)%>
  <div class="mt-5 p-4 text-white statistics-info">
    <h2>統計情報</h2>
    <div class="d-flex justify-content-between gap-3 mt-4">
      <div class="p-4 w-100 statistics-info-card">
        <div class="d-flex align-items-center justify-content-between mb-2">
          <h5 class="mb-0">累計支払額</h5>
          <i class="bi bi-cash-coin ms-2 statistics-icon-blue"></i>
        </div>
        <p>¥<%= number_with_delimiter(@subscription.payments.total_amount.to_i) %></p>
      </div>
      <div class="p-4 w-100 statistics-info-card">
        <div class="d-flex align-items-center justify-content-between mb-2">
          <h5 class="mb-0">次回支払額</h5>
          <i class="bi bi-credit-card-2-front ms-2 statistics-icon-purple"></i>
        </div>
        <p>¥<%= number_with_delimiter(@subscription.price.to_i) %></p>
      </div>
      <div class="p-4 w-100 statistics-info-card">
        <div class="d-flex align-items-center justify-content-between mb-2">
          <h5 class="mb-0">利用月数</h5>
          <i class="bi bi-calendar3 ms-2 statistics-icon-green"></i>
        </div>
        <p>13ヶ月</p>
      </div>
    </div>
  </div>
  <div class="pb-5">
    <div class="mt-5 p-4 text-white border border-dark-subtle rounded">
      <h2><%= Payment.model_name.human %></h2>
      <div class="mt-4 border-start border-end border-top rounded border-dark-subtle">
        <table class="table rounded overflow-hidden bg-color-navy">
          <thead>
            <tr>
              <th scope="col" class="table-header-bg-dark p-3"><%= Payment.human_attribute_name(:billing_date) %></th>
              <th scope="col" class="table-header-bg-dark p-3"><%= Payment.human_attribute_name(:plan) %></th>
              <th scope="col" class="table-header-bg-dark p-3"><%= Payment.human_attribute_name(:billing_cycle) %></th>
              <th scope="col" class="table-header-bg-dark p-3"><%= Payment.human_attribute_name(:amount) %></th>
              <th scope="col" class="table-header-bg-dark p-3"><%= Payment.human_attribute_name("payment_method.provider") %></th>
            </tr>
          </thead>
          <tbody>
            <% @subscription.payments.includes(:payment_method).order(billing_date: :desc).each do |payment| %>
              <tr>
                <td class="table-bg-navy p-3"><%= payment.billing_date.strftime("%Y年%m月%d日") %></td>
                <td class="table-bg-navy p-3"><%= payment.plan %></td>
                <td class="table-bg-navy p-3"><%= payment.billing_cycle %>ヶ月</td>
                <td class="table-bg-navy p-3">¥<%= number_with_delimiter(payment.amount.to_i) %></td>
                <td class="table-bg-navy p-3"><%= payment.payment_method.provider %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>