config/routes.rb
Rails.application.routes.draw do
  root "dashboard#index"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users do
    resources :subscriptions
    resources :tags
    resources :payment_methods
  end
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg px-5 pb-2 pt-3" style="background-color: black;">
  <div class="container-fluid">
    <%= link_to "SubsManager", root_path, class: "navbar-brand text-white" %>
    <% if logged_in? %>
      <div class="dropdown">
        <div class="btn btn-secondary rounded-circle p-2 d-flex justify-content-center align-items-center" type="button" data-bs-toggle="dropdown" aria-expanded="false" style="width: 50px; height: 50px;">
          <i class="bi bi-person" style="font-size: 1.5rem"></i>
        </div>
        <ul class="dropdown-menu dropdown-menu-lg-end p-3" data-bs-theme="dark">
          <span class="dropdown-header text-white fs-5 p-0">
            <%= current_user.name %>
          </span>
          <li><hr class="dropdown-divider text-white"></li>
          <li>
            <%= link_to current_user, class: "dropdown-item text-white rounded-2 d-flex align-items-center" do %>
              <i class="bi bi-person me-2" style="font-size: 1.3rem"></i> プロフィール
            <% end %>
          </li>
          <li>
            <%= link_to user_subscriptions_path(current_user), class: "dropdown-item text-white rounded-2 d-flex align-items-center" do %>
              <i class="bi bi-list-task me-2" style="font-size: 1.3rem"></i> サブスクリプション
            <% end %>
          </li>
          <li>
            <%= link_to logout_path, data: { "turbo-method": :delete}, class: "dropdown-item text-white rounded-2 d-flex align-items-center" do %>
              <i class="bi bi-box-arrow-right me-2" style="font-size: 1.3rem"></i> ログアウト
            <% end %>
          </li>
        </ul>
      </div>
    <% else %>
      <div class="d-flex gap-3">
        <%= link_to new_user_path, class: "text-white text-decoration-none d-flex align-items-center gap-2" do %>
          <i class="bi bi-person-plus" style="font-size: 1.5rem"></i> 新規登録
        <% end %>
        <%= link_to login_path, class: "text-white text-decoration-none d-flex align-items-center gap-2" do %>
          <i class="bi bi-box-arrow-in-right" style="font-size: 1.5rem"></i> ログイン
        <% end %>
      </div>
    <% end %>
  </div>
</nav>

<% if logged_in? %>
<nav id="sub-nav">
  <ul class="nav">
    <li class="nav-item">
      <%= link_to root_path, class: "nav-link #{dashboard_tab? ? "active" : ""}" do %>
        <i class="bi bi-house"></i> ホーム
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to user_subscriptions_path(current_user), class: "nav-link #{subscriptions_tab? ? "active" : ""}" do %>
        <i class="bi bi-list-task"></i> サブスクリプション
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to user_tags_path(current_user), class: "nav-link #{tags_tab? ? "active" : ""}" do %>
        <i class="bi bi-tags"></i> タグ
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to user_payment_methods_path(current_user), class: "nav-link #{payment_methods_tab? ? "active" : ""}" do %>
        <i class="bi bi-credit-card"></i> 支払い方法
      <% end %>
    </li>
  </ul>
  </nav>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Subscription Management" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": Rails.env.production? ? "reload" : "" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div id="content">
      <% flash.each do |message_type, message| %>
        <div class="p-3">
          <div class="alert alert-<%= message_type %> m-0"><%= message %></div>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>